oracle:
  enable: true
  connections:
    - name: "oracle_prod"
      host: "localhost"
      port: 1521
      enable: false
      username: "test"
      password: "test123"
      service_name: "TESTDB"
      retry_attempts: 3
      retry_delay: 1.0
      connection_timeout: 30.0

command:
  enable: true
  connections:
    - name: "remote_command_prod"
      host: "api.example.com"
      port: 443
      enable: false
      api_key: "your-api-key"
      api_version: "v1"
      retry_attempts: 3
      retry_delay: 1.0
      connection_timeout: 30.0

search:
  enable: true
  connections:
    - name: "pattern_search_prod"
      host: "search.example.com"
      port: 8080
      enable: false
      search_timeout: 60.0
      max_results: 100
      retry_attempts: 3
      retry_delay: 1.0
      connection_timeout: 30.0

quickfix:
  enable: true
  connections:
    - name: "quickfix_prod"
      enable: true
      config_file_name: "test.cfg"
      retry_attempts: 3
      retry_delay: 1.0

remote_database:
  enable: false
  connections:
    - name: "remote_database_prod"
      enable: true
      host: 'localhost'
      port: 9001
      retry_attempts: 10
      retry_delay: 1.0
      timeout: 30.0

imix:
  enable: false
  connections:
    - name: "imix_prod"
      enable: false
      host: "imix.example.com"
      port: 8080
      username: "admin"
      password: "admin123"
      retry_attempts: 3
      retry_delay: 1.0
      connection_timeout: 30.0
